### ISSUE TITLE
Installing from zip: fails to import xarray and flopy

### ISSUE THREAD

**Issue by Huite** [dzamrsky/SWAMPy-tools#1]
When installing from the zip, I immediately get an ``ModuleNotFoundError: No module named 'flopy'``.

I see that in the zip you do "vendor" a number of packages yourself (as they call it). Accordingly in the first module I looked, xarray is a relative import -- but flopy isn't?

```python
from .. import xarray as xr
import statistics
from statistics import StatisticsError
#from qgis.core import QgsTask
import flopy
import flopy.utils.binaryfile as bf
```

To fix it now, I just called the `py_env3.bat` and `python-qgis.bat` (located in `c:\Program Files\QGIS 3.18\bin`) and then installed flopy and xarray using pip. The plugin then install correctly.

(I'm honestly not sure what the easiest way of dealing with dependencies is on the long term, pip still doesn't seem like an obvious option if you read through this: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/202)

**Comment by dzamrsky** [comment]
Hi Huite, sorry for the late reply (i guess this is not even a valid excuse since i missed the 1 year reply deadline, albeit only by few days!). SWAMPy was unfortunately hibernating in the past year but now is being awaken again, hopefully for a long time.

I saw that there was an error when installing the plugin - linked to the xarray package. I hope i managed to solve it by manually adding the directory where the plugin is installed as follows:

import sys, os
sys.path.append(os.path.dirname(__file__))

It worked when I tried to install the plugin on my computer so hopefully it will work for you as well. Let me know if you run into some other issues, I promise I will do my best to reply faster :)

Cheers, Daniel
